import re
from dataclasses import dataclass


@dataclass
class RouteDecision:
    route: str
    metric: str | None = None
    reason: str | None = None


METRIC_PATTERNS = {
    "revenue": [
        r"\brevenue\b",
        r"\bnet sales\b",
        r"\btotal sales\b",
    ],
    "net_income": [
        r"\bnet income\b",
        r"\bnet profit\b",
    ],
    "operating_income": [
        r"\boperating income\b",
        r"\boperating profit\b",
    ],
    "operating_cash_flow": [
        r"\boperating cash flow\b",
        r"\bcash flow from operating activities\b",
        r"\bcash generated by operating activities\b",
        r"\bnet cash provided by operating activities\b",
    ],
    "total_assets": [
        r"\btotal assets\b",
    ],
    "total_liabilities": [
        r"\btotal liabilities\b",
    ],
}


RAG_INDICATORS = [
    "why",
    "how",
    "explain",
    "reason",
    "reasons",
    "driver",
    "drivers",
    "risk",
    "risks",
    "discuss",
    "describe",
    "outlook",
    "strategy",
    "challenge",
    "challenges",
    "increase because",
    "decrease because",
    "changed because",
]


def detect_metric(question: str) -> str | None:
    """
    Detect one supported financial KPI from the question.
    """

    question_lower = question.lower()

    for metric, patterns in METRIC_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, question_lower):
                return metric

    return None


def route_query(
    question: str,
    company: str | None,
    year: int | None,
) -> RouteDecision:
    """
    Route a question to structured PostgreSQL lookup or RAG.

    Structured routing is intentionally conservative:
    - one supported KPI
    - company is known
    - fiscal year is known
    - question is asking for the value rather than explanation
    """

    question_lower = question.lower()

    # Explanation / qualitative questions should use filing evidence.
    if any(indicator in question_lower for indicator in RAG_INDICATORS):
        return RouteDecision(
            route="rag",
            reason="Question requires qualitative or explanatory evidence.",
        )

    metric = detect_metric(question)

    # Structured path needs a specific metric + company + year.
    if metric and company and year:
        return RouteDecision(
            route="structured",
            metric=metric,
            reason="Direct KPI lookup with company and fiscal year.",
        )

    return RouteDecision(
        route="rag",
        reason="Question does not meet structured lookup requirements.",
    )